# Generated by Django 2.2.24 on 2021-11-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.AlterField(
            model_name='profile',
            name='breed',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='species',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='trait',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
