# Generated by Django 2.2.24 on 2021-11-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20211118_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userAva',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
