# Generated by Django 2.2.24 on 2021-11-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_profile_userava'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userAva',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
