# Generated by Django 2.2.24 on 2021-11-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20211122_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userAva',
            field=models.ImageField(blank=True, null=True, upload_to='login/media'),
        ),
    ]
