# Generated by Django 2.2.24 on 2021-11-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20211122_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userAva',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
