# Generated by Django 2.2.24 on 2021-11-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20211124_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='noInteract',
            field=models.TextField(blank=True, default=''),
        ),
    ]
